### PR TITLE
Fixed AttributeError: 'int' object has no attribute 'is_sick' and more

### PR DESCRIPTION
**Pull request by Nalin-Angrish**
Fixed AttributeError: 'int' object has no attribute 'is_sick' and AttributeError: 'int' object has no attribute 'has_antibodies' . Told humans to remove masks and quit quarantine after the disease has been cured.

### CODE REVIEW

**Comment by Nalin-2005** [comment]
I saw that you have created the remove_sickness.py, and it is optimized for the world now. Just asking, but when will this script be executed?

**Comment by CompuGenius** [comment]
Thanks so much for the pull request! I was unable to run the code before submitting as I was unsure whether @god would punish my soul for eternity. Hopefully, he accepts your pull request and runs it as soon as possible!

**Comment by god** [comment]
As it's a Friday, I am obligated to be merciful and just. Mondays, on the other hand...

**Comment by Nalin-Angrish** [comment]
@god I understand what Mondays make u feel. But you are god.... so you can actually remove Mondays right? What are you waiting for?

**Pull request merged**
