### PR TITLE
preventing karens, anti vaxxers, anti maskers

### PR DESCRIPTION
**Pull request by Kabir-Sidhu**

### CODE REVIEW

**Comment by stingalleman** [comment]
why can't you just turn off covid

**Comment by Kabir-Sidhu** [comment]
> why can't you just turn off covid

I tried, but it throws an error. "CovidError: Covid is immortal, can not turn off."

**Comment by Kabir-Sidhu** [comment]
> > why can't you just turn off covid
> 
> I tried, but it throws an error. "CovidError: Covid is immortal, can not turn off."

idk how to fix it ;-;

**Comment by stingalleman** [comment]
> I tried, but it throws an error. "CovidError: Covid is immortal, can not turn off."

Just sudo it

**Comment by Kabir-Sidhu** [comment]
> > I tried, but it throws an error. "CovidError: Covid is immortal, can not turn off."
> 
> Just sudo it

I don't got the pass m8 :c

**Comment by god** [comment]
the password is 69420

**Pull request closed without merging**
